/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controlador.ControladorCliente;
import Controlador.ControladorFactura;
import Controlador.ControladorTipoCliente;
import Grillas.GrillaTipoCliente;
import Objeto.TipoCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Fefe
 */
public class VentanaTipoCliente extends javax.swing.JInternalFrame {
    private ControladorFactura cf = new ControladorFactura();
    private ControladorCliente cc = new ControladorCliente();
    private ControladorTipoCliente ctc = new ControladorTipoCliente();
    private Integer rowSelect = null;
    private TipoCliente objtipo = new TipoCliente();

    /**
     * Creates new form VentanaTipoCliente
     */
    public VentanaTipoCliente() {
        initComponents();
        
        grilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaTipo = new javax.swing.JTable();
        jbEliminar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();

        jLabel1.setText("Descripcion");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jtTablaTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaTipoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaTipo);

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(11, 11, 11)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbEliminar)
                            .addComponent(jbModificar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbGuardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jbModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        
        
        
        
        ctc.Guardar(formularioTipo());
        grilla();
        
        
        
        
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if(rowSelect != null){
            
            cc.EliminarTipoCliente(rowSelect);
            ctc.Eliminar(rowSelect);
            
            JOptionPane.showMessageDialog(rootPane, "Se elimino correctamente");
            grilla();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccioné un cliente");
        }
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtTablaTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaTipoMouseClicked
        // TODO add your handling code here:
        
        rowSelect = (Integer) jtTablaTipo.getValueAt(jtTablaTipo.getSelectedRow(), 1); 
        objtipo = ctc.mostrar(rowSelect);
           jtDescripcion.setText(objtipo.getDescripcion());
        
    }//GEN-LAST:event_jtTablaTipoMouseClicked

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
        
        
         if(rowSelect != null){
            TipoCliente tc =  formularioTipo();
            tc.setId(rowSelect);
            ctc.Modificar(tc);
            JOptionPane.showMessageDialog(rootPane, "Se Modifico");
            grilla();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccioné un cliente");
        }
        
        
    }//GEN-LAST:event_jbModificarActionPerformed

     private TipoCliente formularioTipo (){
        TipoCliente tc = new TipoCliente();
        
        tc.setDescripcion(jtDescripcion.getText());
         return tc;
    }
    
    
    
     private void grilla(){
    
         GrillaTipoCliente gt;
        gt = new GrillaTipoCliente(ctc.MostrarTodo());
        jtTablaTipo.setModel(gt);
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTable jtTablaTipo;
    // End of variables declaration//GEN-END:variables
}
