/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controlador.ControladorCategoria;
import Controlador.ControladorRenglon;
import Controlador.ControladorProducto;
import Grillas.GrillaCategoria;
import Objeto.Categoria;
import Objeto.Renglon;
import Objeto.Producto;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabry
 */
public class VentanaCategoria extends javax.swing.JInternalFrame {
    
     Categoria categ = new Categoria();
    private Controlador.ControladorCategoria cc = new ControladorCategoria();
    ArrayList<Categoria> alCateg = new ArrayList<>();
    private ControladorRenglon cd = new ControladorRenglon();
    private ControladorProducto cp = new ControladorProducto();
    private Integer rowSelect = null;
    private Categoria objCate = new Categoria();
    

    /**
     * Creates new form Ventana
     */
    public VentanaCategoria() {
        initComponents();
        grilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtablaCategoria = new javax.swing.JTable();
        jDescripcion = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();

        jLabel2.setText("Descripcion");

        JtablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JtablaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtablaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtablaCategoria);

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(jDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbEliminar)
                                    .addComponent(jbGuardar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbModificar)
                                .addGap(2, 2, 2)))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jbGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Integer filas;
    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
    
        cc.Guardar(formularioCatagoria());
        grilla();
    
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void JtablaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtablaCategoriaMouseClicked
        // TODO add your handling code here:
        
        
        rowSelect = (Integer) JtablaCategoria.getValueAt(JtablaCategoria.getSelectedRow(), 1); 
        
        objCate = cc.mostrar(rowSelect);
           jDescripcion.setText(objCate.getDescripcion());
        
        
    }//GEN-LAST:event_JtablaCategoriaMouseClicked

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
       if(rowSelect != null){
            ArrayList<Renglon> detalles = cd.MostrarTodoDetalleProducto(rowSelect);
            ArrayList<Producto> productos = cp.MostrarTodoProductoCate(rowSelect);
            ControladorRenglon cd = new ControladorRenglon();
            
            for (Renglon detalle : detalles) {
                cd.EliminarProducto(detalle.getId());
            } 
            for (Producto producto : productos ){
                cp.EliminarCategoria(producto.getId());
            } 
            cp.Eliminar(rowSelect);
            cd.Eliminar(rowSelect);
            cc.Eliminar(rowSelect);
            JOptionPane.showMessageDialog(rootPane, "Se elimino correctamente");
            grilla();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccioné un cliente");
        }
        
        
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        // TODO add your handling code here:
         if(rowSelect != null){
            Categoria c =  formularioCatagoria();
            c.setId(rowSelect);
            cc.Modificar(c);
            JOptionPane.showMessageDialog(rootPane, "Se Modifico");
            grilla();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Seleccioné un cliente");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

      private Categoria formularioCatagoria (){
          
        Categoria cate = new Categoria();
        cate.setDescripcion(jDescripcion.getText());
         return cate;
    }

    private void grilla(){
    
        GrillaCategoria gc;
        gc = new GrillaCategoria(cc.MostrarTodo());
        JtablaCategoria.setModel(gc);
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtablaCategoria;
    private javax.swing.JTextField jDescripcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    // End of variables declaration//GEN-END:variables
}
